export const FETCH_START = 'FETCH_START';
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT';
export const FETCH_SEARCH_RESULT_FAILED = 'FETCH_SEARCH_RESULT_FAILED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';